### ISSUE TITLE
Typer should be smart about replacing parts of the string

### ISSUE THREAD

**Issue by allang** [layervault/jquery.typer.js#1]
Typer should only highlight as far back as necessary. If the string is being replaced by a slightly modified version, go back only as far as needed to. Example:

If the string is going from "Lorem-Ipsum.psd" to "Lorem-Dolor.psd", typer should only highlight "Ipsum.psd" and replace it with "Dolor.psd"

**Comment by kellysutton** [comment]
Implemented. Examples on test.html.
